# Generated by Django 6.0.2 on 2026-02-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=15, unique=True)),
                ('vehicle_type', models.CharField(choices=[('Matatu', 'Matatu'), ('Bus', 'Bus')], max_length=10)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Unroadworthy', 'Unroadworthy')], default='Active', max_length=15)),
                ('unroadworthy_sub_status', models.CharField(blank=True, choices=[('Fixed', 'Fixed'), ('Fixer-Upper', 'Fixer-Upper')], max_length=15, null=True)),
                ('condition_report', models.TextField(blank=True, help_text='Detailed assessment of the vehicle condition.')),
                ('driver_assigned', models.BooleanField(default=True)),
                ('license_expired', models.BooleanField(default=False)),
                ('maintenance_due', models.BooleanField(default=False)),
            ],
        ),
    ]
